"""
Projects module -- the gap this closes: every other BuildPolaris DocType
(Task, RFI, Commitment, Submittal Package, Punch List Item, Safety
Incident, Pay Application, Closing Record, ...) carries a `project` Link
field, and buildpolaris_bff's own ERD documents `Project` as a native
ERPNext entity (ERD §"Project" <<native>>) -- but no use case, no FR, and
no api.py anywhere ever created one. This module is that missing piece.

Deliberately built on ERPNext v16's native Project DocType rather than a
BuildPolaris-authored one, per the same "extend, don't shadow" discipline
ERD §"WBS" already applies to Task: "Extended with custom fields
(create_custom_fields, NFR-MAINT.4) ... never a shadow schedule table."
Native Project already carries everything this module needs
(project_name, status, expected_start_date/expected_end_date,
percent_complete, company) -- no new custom fields were needed on Project
itself; see patches/v1_0/fix_project_naming.py for the one native-schema
adjustment this module DOES make (multi-tenant naming collision fix).

Every function here follows the same discipline as every other module's
services/: assert_project_permission/assert_role BEFORE any mutation,
company resolved server-side from the acting user's own bp_company (never
trusted from the client), never a raw frappe.get_all without a Project/
Company filter.
"""
import frappe
from frappe.utils import today

from buildpolaris_bff.shared.exceptions import ValidationError
from buildpolaris_bff.shared.permissions import assert_project_permission, assert_role, get_assigned_projects


def _acting_company(user: str) -> str | None:
	if not frappe.db.has_column("User", "bp_company"):
		return None
	return frappe.db.get_value("User", user, "bp_company")


def create_project(project_name: str, description: str | None = None,
                    expected_start_date: str | None = None, expected_end_date: str | None = None,
                    created_by: str | None = None) -> dict:
	"""FR-gap closed: creates the Project every other module's `project`
	Link field points at. Company is resolved from the CREATING user's own
	tenant (bp_company) -- never accepted from the client, same discipline
	mint_scope_assertion() already applies (shared/scope_assertion.py) so
	a Project can never be created against a company the caller doesn't
	belong to.

	buildpolaris_pwa's CreateProjectDialog.tsx already sends exactly this
	payload shape ({project_name, description, expected_start_date,
	expected_end_date}) -- it was calling a createProject() that didn't
	exist client-side and an endpoint that didn't exist server-side.
	"""
	created_by = created_by or frappe.session.user
	assert_role("BuildPolaris Admin", "BuildPolaris Owner", "BuildPolaris Project Manager", user=created_by)

	company = _acting_company(created_by)
	if not company:
		raise ValidationError(
			"Your user account has no Company assigned - a Project cannot be "
			"created without a tenant Company to attach it to. Contact an Admin."
		)

	if not project_name or not project_name.strip():
		raise ValidationError("project_name is required.")

	doc = frappe.get_doc({
		"doctype": "Project",
		"project_name": project_name.strip(),
		"company": company,
		"status": "Open",
		"expected_start_date": expected_start_date or None,
		"expected_end_date": expected_end_date or None,
		"notes": description or None,
	})
	# name is auto-generated by the naming series set in
	# patches/v1_0/fix_project_naming.py (PROJ-.YYYY.-.#####) -- NOT
	# project_name, which stays a free-text label and does not need to be
	# globally unique across tenants sharing this site.
	doc.insert()

	return doc.as_dict()


def get_project(project: str, user: str | None = None) -> dict:
	user = user or frappe.session.user
	assert_project_permission(project, ptype="read", user=user)
	return frappe.get_doc("Project", project).as_dict()


def list_projects(status: str | None = None, user: str | None = None) -> list:
	"""Lists Projects the caller can see. Mirrors
	shared/permissions.get_assigned_projects()'s own documented semantics:
	a user with no restricting User Permission rows sees every Project in
	their Company (Frappe's own default), not an empty list -- explicit
	per-Project restriction is an opt-in via identity's assign_project(),
	not the default posture."""
	user = user or frappe.session.user
	company = _acting_company(user)

	filters: dict = {}
	if company and "System Manager" not in frappe.get_roles(user):
		filters["company"] = company
	if status:
		filters["status"] = status

	assigned = get_assigned_projects(user)
	rows = frappe.get_all(
		"Project", filters=filters,
		fields=["name", "project_name", "status", "expected_start_date", "expected_end_date",
		        "percent_complete", "company"],
		order_by="creation desc",
	)
	if assigned:
		rows = [r for r in rows if r.name in assigned]
	return rows


def update_project(project: str, updates: dict, updated_by: str | None = None) -> dict:
	updated_by = updated_by or frappe.session.user
	assert_project_permission(project, ptype="write", user=updated_by)
	assert_role("BuildPolaris Admin", "BuildPolaris Owner", "BuildPolaris Project Manager", user=updated_by)

	doc = frappe.get_doc("Project", project)
	allowed_fields = {"project_name", "status", "expected_start_date", "expected_end_date",
	                   "priority", "notes", "percent_complete"}
	for key, value in (updates or {}).items():
		if key in allowed_fields:
			doc.set(key, value)
	doc.save()
	return doc.as_dict()
